[package]
name = "brainfuck-extended"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
crossterm = "0.27.0"
ctrlc = "3.4.1"
